### ISSUE TITLE
Atribute error

### ISSUE THREAD

**Issue by nicolasperezdeo** [cheriimoya/SpotifyRecorder#1]
After running got the following error:

> AttributeError: module 'gobject' has no attribute 'MainLoop'

**Comment by nicolasperezdeo** [comment]
I think it is a problem with my dbus installation. Could you please look at this? 
![image](https://user-images.githubusercontent.com/32769401/59924689-962a2500-9436-11e9-9808-8ca32526675c.png)

**Comment by nicolasperezdeo** [comment]
Added pygobject that was missing. Still same error. 

![image](https://user-images.githubusercontent.com/32769401/59925443-6d0a9400-9438-11e9-8974-2b74421c94cb.png)

**Comment by cheriimoya** [comment]
hi, i'll look into it asap:)

**Comment by nicolasperezdeo** [comment]
Cool, thanks. Working in Ubuntu 18.04.2 LTS. :)

**Comment by cheriimoya** [comment]
I think the problem was, that i was using pygobject version 2 instead of version 3, i'll update that...
What OS and version did you use when you encountered the Attribute error?

**Comment by nicolasperezdeo** [comment]
Ok! It looks that Pyobject version 2 is not available anymore. I was using Ubuntu 18.04.2 LTS. Thanks for the update. Let me know the update.

**Comment by cheriimoya** [comment]
Could you please try b66c3cf with pygobject3 and see if this fixes it?

**Comment by nicolasperezdeo** [comment]
Yep, solves the problem! Thanks :+1:

**Comment by cheriimoya** [comment]
Closed by a8096e8
